name: Build and Check

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: build and check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Code formatting
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Svelte Check
        run: npm run check
